import type { AuditResult } from '../types.js';

export function generateZodSchema(result: AuditResult): string {
  const allVarNames = Array.from(
    new Set([
      ...result.codeUsages.map((u) => u.name),
      ...result.definedVariables.filter((d) => !d.isCommentedOut).map((d) => d.name),
    ])
  ).sort();

  const fields: string[] = [];

  for (const varName of allVarNames) {
    const upper = varName.toUpperCase();
    if (upper === 'NODE_ENV') {
      fields.push(`  ${varName}: z.enum(['development', 'production', 'test']).default('development'),`);
    } else if (upper.includes('PORT')) {
      fields.push(`  ${varName}: z.coerce.number().int().positive().default(3000),`);
    } else if (upper.includes('URL') || upper.includes('URI')) {
      fields.push(`  ${varName}: z.string().url().min(1),`);
    } else if (upper.startsWith('IS_') || upper.startsWith('ENABLE_') || upper.startsWith('USE_') || upper.startsWith('DEBUG')) {
      fields.push(`  ${varName}: z.enum(['true', 'false', '1', '0']).transform(v => v === 'true' || v === '1').default('false'),`);
    } else if (upper.includes('TIMEOUT') || upper.includes('LIMIT') || upper.includes('COUNT')) {
      fields.push(`  ${varName}: z.coerce.number().default(10),`);
    } else {
      fields.push(`  ${varName}: z.string().min(1),`);
    }
  }

  return `// Auto-generated by GhostConfig
import { z } from 'zod';

export const envSchema = z.object({
${fields.join('\n')}
});

export type Env = z.infer<typeof envSchema>;

export function validateEnv(env = process.env): Env {
  const parsed = envSchema.safeParse(env);
  if (!parsed.success) {
    console.error('❌ Invalid environment variables:', parsed.error.flatten().fieldErrors);
    throw new Error('Invalid environment configuration');
  }
  return parsed.data;
}
`;
}

export function generateTypeScriptDeclaration(result: AuditResult): string {
  const allVarNames = Array.from(
    new Set([
      ...result.codeUsages.map((u) => u.name),
      ...result.definedVariables.filter((d) => !d.isCommentedOut).map((d) => d.name),
    ])
  ).sort();

  const lines: string[] = [];
  lines.push('// Auto-generated by GhostConfig');
  lines.push('declare global {');
  lines.push('  namespace NodeJS {');
  lines.push('    interface ProcessEnv {');

  for (const varName of allVarNames) {
    if (varName === 'NODE_ENV') {
      lines.push(`      ${varName}?: 'development' | 'production' | 'test';`);
    } else {
      lines.push(`      ${varName}?: string;`);
    }
  }

  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('export {};');
  lines.push('');

  return lines.join('\n');
}
